export enum RouterConstants {
  ROOT = '/',
  AUTH = '/auth',
  EDIT = '/edit',
  ABOUT = '/about',
  ALL_COURSES = '/courses',
  ADD = '/add',
  CART = '/cart',
  REMOVE = '/remove',
  ORDERS = '/orders',
  LOGIN = '/login',
  LOGOUT = '/logout',
  REGISTER = '/register',
  RESET = '/reset',
  RECOVERY = '/recovery',
  BY_ID = '/:id',
  EDIT_BY_ID = '/:id/edit',
  HAS_LOGIN = '#login',
  HAS_REGISTER = '#register'
}
